<script setup>
import { idToGkId } from '../../composables/useGkId.js'
import { gkAvatarUrl } from '../../composables/useAvatarUrl.js'
import Pagination from '../Pagination.vue'
import PointsValue from '../PointsValue.vue'
import GkTypeBadge from '../GkTypeBadge.vue'
import AwardingOnlyToggle from '../AwardingOnlyToggle.vue'
import GeokretTypeFilterDropdown from '../GeokretTypeFilterDropdown.vue'

const props = defineProps({
  geokrety: { type: Array, default: () => [] },
  meta: { type: Object, default: () => ({}) },
  loading: { type: Boolean, default: false },
  sortCol: { type: String, default: 'last_interaction' },
  sortOrder: { type: String, default: 'desc' },
  awardingOnly: { type: Boolean, default: false },
  multiplierOnly: { type: Boolean, default: false },
  selectedTypes: { type: Array, default: () => [] }
})

const emit = defineEmits(['update:page', 'toggle-sort', 'update:awarding-only', 'update:multiplier-only', 'update:selected-types'])

function toggleSort(col, ascDefaults = []) {
  emit('toggle-sort', col, ascDefaults)
}

function sortIcon(col) {
  if (props.sortCol !== col) return 'bi-sort-down'
  return props.sortOrder === 'asc' ? 'bi-sort-up-alt' : 'bi-sort-down-alt'
}
</script>

<template>
  <div>
    <div class="d-flex flex-wrap gap-2 align-items-center mb-2">
      <AwardingOnlyToggle :model-value="awardingOnly" @update:model-value="v => emit('update:awarding-only', v)" />
      <button type="button" class="btn btn-sm" :class="multiplierOnly ? 'btn-primary' : 'btn-outline-secondary'" title="Show only GeoKrety with multiplier above 1" @click="emit('update:multiplier-only', !multiplierOnly)">
        <i class="bi bi-graph-up me-1"></i>Only multiplier >1
      </button>
      <GeokretTypeFilterDropdown :model-value="selectedTypes" @update:model-value="v => emit('update:selected-types', v)" id-prefix="user-gk-type" />
    </div>

    <div class="card shadow-sm border-0">
      <div class="table-responsive border-0 mb-0">
        <table class="table table-hover table-sm mb-0 align-middle border">
          <thead class="table-dark">
            <tr>
              <th class="ps-3" style="cursor:pointer" @click="toggleSort('gk', ['gk'])" :class="sortCol==='gk' ? 'text-warning' : ''" title="GeoKret name">GeoKret <i class="bi" :class="sortIcon('gk')"></i></th>
              <th class="d-none d-md-table-cell" style="cursor:pointer" @click="toggleSort('type', ['type'])" :class="sortCol==='type' ? 'text-warning' : ''" title="GeoKret type">Type <i class="bi" :class="sortIcon('type')"></i></th>
              <th class="d-none d-sm-table-cell" style="cursor:pointer" @click="toggleSort('last_interaction')" :class="sortCol==='last_interaction' ? 'text-warning' : ''" title="Latest interaction date by this user">Last interaction <i class="bi" :class="sortIcon('last_interaction')"></i></th>
              <th class="text-end" style="cursor:pointer" @click="toggleSort('points')" :class="sortCol==='points' ? 'text-warning' : ''" title="Total points generated by this GeoKret">Points Generated <i class="bi" :class="sortIcon('points')"></i></th>
              <th class="text-end pe-3" style="cursor:pointer" @click="toggleSort('multiplier')" :class="sortCol==='multiplier' ? 'text-warning' : ''" title="Current GeoKret multiplier">Multiplier <i class="bi" :class="sortIcon('multiplier')"></i></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="g in geokrety" :key="g.gk_id" @click="$router.push(`/geokrety/${g.gk_id}`)" style="cursor: pointer">
              <td class="ps-3">
                <div class="d-flex align-items-center gap-2">
                  <img v-if="gkAvatarUrl(g.avatar)" :src="gkAvatarUrl(g.avatar)" :alt="`${g.gk_name || idToGkId(g.gk_id)} avatar`" class="gk-thumb" />
                  <div>
                    <RouterLink :to="`/geokrety/${g.gk_id}`" class="fw-bold text-decoration-none" @click.stop>{{ g.gk_name || idToGkId(g.gk_id) }}</RouterLink>
                    <div class="small text-muted">#{{ g.gk_id }}</div>
                  </div>
                </div>
              </td>
              <td class="d-none d-md-table-cell"><GkTypeBadge :gk-type="g.gk_type" /></td>
              <td class="d-none d-sm-table-cell small text-muted">{{ g.last_interaction ? String(g.last_interaction).slice(0, 10) : '—' }}</td>
              <td class="text-end fw-semibold"><PointsValue :value="g.total_points_generated" /></td>
              <td class="text-end pe-3">{{ Number(g.current_multiplier || 1).toFixed(2) }}×</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <Pagination v-if="meta.total" :meta="meta" :page="meta.page" @update:page="p => emit('update:page', p)" class="mt-3" />
  </div>
</template>

<style scoped>
.gk-thumb {
  width: 26px;
  height: 26px;
  border-radius: 50%;
  object-fit: cover;
  border: 1px solid var(--bs-border-color);
  flex-shrink: 0;
}
</style>
