---
services:
  api:
    build: .
    container_name: geokrety-stats-api
    ports:
      - "7415:7415"
    environment:
      - PGHOST=192.168.130.65
      - PGPASSWORD=geokrety
      - LOG_LEVEL=debug
    restart: unless-stopped
